### PR TITLE
101 functionality in images for image labeling

### PR DESCRIPTION
**Pull request by orvintritama**

### CODE REVIEW

**Review by ryanlu-ubc — APPROVED** [review]
great work! there is a bear

**Review by Shiyastra — APPROVED** [review]
Amazing work! There is indeed a bear

**Review by qingyan-hu — DISMISSED** [review]
Well done!

**Review by qingyan-hu — APPROVED** [review]
well done!

**Review by ryanlu-ubc — APPROVED** [review]
great work. I love the bear

**Review by Shiyastra — APPROVED** [review]
Thank you so much!

**Pull request merged**
