### PR TITLE
Added research of Angular and D3

### PR DESCRIPTION
**Pull request by qingyan-hu**
Added intro, examples, advantages, why and prerequisites of Angular and D3

### CODE REVIEW

**Review by ryanlu-ubc — APPROVED** [review]
Well documented.

**Review by orvintritama — APPROVED** [review]
nice documentation!

**Review by ryanlu-ubc — DISMISSED** [review]
Good document!

**Review by Shiyastra — APPROVED** [review]
Document looks great!

**Review by ryanlu-ubc — APPROVED** [review]
Detailed document!

**Review by orvintritama — APPROVED** [review]
Thanks for adding prerequisites!

**Pull request merged**
