### PR TITLE
Updated part of deliverable #1

### PR DESCRIPTION
**Pull request by qingyan-hu**

### CODE REVIEW

**Review by orvintritama — DISMISSED** [review]
looks good!

**Review by orvintritama — DISMISSED** [review]

**Review by orvintritama — APPROVED** [review]

**Review by Shiyastra — APPROVED** [review]
Good updates

**Review by ryanlu-ubc — APPROVED** [review]
This is really good!

**Comment by ryanlu-ubc** [comment]
I really like the new version of this.

**Pull request merged**
