### PR TITLE
92 create a css file as shared resource used in the html files as per rosens styling

### PR DESCRIPTION
**Pull request by orvintritama**
starting shared styling for ROSEN-A

### CODE REVIEW

**Review by Shiyastra — APPROVED** [review]
Thanks for adding styling!

**Review by qingyan-hu — APPROVED** [review]
Very efficient!

**Review by ryanlu-ubc — APPROVED** [review]
Great code!

**Comment by ryanlu-ubc** [comment]
I will use this in my index.html

**Pull request merged**
