### PR TITLE
Updated framecount page

### PR DESCRIPTION
**Pull request by ryanlu-ubc**
(GBAGE)

### CODE REVIEW

**Review by qingyan-hu — APPROVED** [review]
Wow, amazing work!

**Review by orvintritama — COMMENTED** [review]
awesome changes

**Review by orvintritama — DISMISSED** [review]

**Review by Shiyastra — APPROVED** [review]
Cool!

**Review by Shiyastra — APPROVED** [review]
Good work!

**Review by orvintritama — APPROVED** [review]

**Review by qingyan-hu — APPROVED** [review]
Great work!!!

**Pull request merged**
