### PR TITLE
added schema and collections

### PR DESCRIPTION
**Pull request by qingyan-hu**

### CODE REVIEW

**Review by ryanlu-ubc — APPROVED** [review]
fantastic work!

**Review by Shiyastra — DISMISSED** [review]
Thank you for the detailed additions!

**Review by orvintritama — APPROVED** [review]
wow, this is awesome work. Thanks a lot Qingyan!

**Review by ryanlu-ubc — APPROVED** [review]
fantastic work again

**Review by orvintritama — APPROVED** [review]
thanks again!!

**Review by Shiyastra — APPROVED** [review]
Looks good!

**Pull request merged**
