### PR TITLE
frameCount.html

### PR DESCRIPTION
**Pull request by ryanlu-ubc**
please forget the bear. apparently there's garbage

### CODE REVIEW

**Review by qingyan-hu — APPROVED** [review]
Thank you :3

**Review by Shiyastra — DISMISSED** [review]
Nice work!

**Review by Shiyastra — APPROVED** [review]
Thanks for resolving!

**Review by orvintritama — APPROVED** [review]
thankss!

**Review by qingyan-hu — APPROVED** [review]
great work!

**Pull request merged**
